# Generated by Django 5.0.1 on 2026-04-27 13:00

import apps.campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.campaigns.models.campaign_attachment_path),
        ),
    ]
